### ISSUE TITLE
Reset progress-bar upon returning to 0 percentage without animation

### ISSUE THREAD

**Issue by tomerzcod7** [kevinsqi/react-circular-progressbar#104]
## 🚀 Feature request
Reset progress bar without animation
### Problem description
Hello, I need a progress bar to count laps (such as in a race). For that, I need the progress bar to completely reset upon returning to 0 without animation, in order to start again from 0.

Is there a way to achieve this?

**Comment by kevinsqi** [comment]
Yup! 

The key is to set the path `transition` style to be `none` when the percentage is going to 0:

```
<CircularProgressbar
  // other props...
  styles={
    path: {
      transition: currentPercentage === 0 ? 'none' : 'stroke-dashoffset 0.5s ease 0s',
    }
  }
/>
```

Here's a working example: https://codesandbox.io/s/react-circular-progressbar-issue-104-no-rewind-animation-jvsv0

Hope this helps! Let me know if you have any further issues around this.

**Comment by tomerzcod7** [comment]
Thank you very much!
