### ISSUE TITLE
CSS not applying

### ISSUE THREAD

**Issue by musicbyjing** [kevinsqi/react-circular-progressbar#105]
I'm using this with the [Dashbling](https://github.com/pascalw/dashbling) framework, which uses [this webpack configuration](https://github.com/pascalw/dashbling/blob/master/packages/build-support/webpack.config.js). I tried importing the CSS file both as a module (`import "react-circular-progressbar/dist/styles.css";`) and locally, but neither seem to work. 
In the first case, it says I don't have the necessary module (`You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders`), and in the second case, CSS styling is not applied to the meter so I just see text.

**Comment by kevinsqi** [comment]
hmm, for the first case (importing CSS module), that's out of scope of this project - it's something related to the Dashbling CSS loader configuration. As far as I can tell, Dashbling should be able to support that CSS import.

For the second case, I'm not sure what you mean by "locally". I'm guessing the CSS isn't being included as expected. You can verify this by inspecting the component in developer tools and seeing if `.CircularProgressbar-*` CSS classes are being applied. It's hard to diagnose without seeing the code or an example that reproduces the problem, so if you'd like more help, please provide one of those.

**Comment by musicbyjing** [comment]
I got it, indeed had to do with the other framework. They were excluding node_modules in the webpack configuration. Thanks for your help!
