### ISSUE TITLE
Multiple colors in single circle

### ISSUE THREAD

**Issue by RahulShahUI** [kevinsqi/react-circular-progressbar#106]
### Problem description

How can i apply multiple colors in single circle like below screenshot.

![circle-img](https://user-images.githubusercontent.com/38944466/61871298-1f34f000-aefe-11e9-8668-3d8b508c4fbf.png)

**Comment by kevinsqi** [comment]
This isn't supported directly in the component, but can be achieved by overlaying two progressbars on top of each other.

Here's an example: https://codesandbox.io/s/react-circular-progressbar-issue-106-snobt

<img width="215" alt="Screen Shot 2019-07-25 at 8 37 34 PM" src="https://user-images.githubusercontent.com/396006/61924307-0e937280-af1c-11e9-893b-05fceef68f3c.png">

Does this cover what you need?

**Comment by AleksandarTisma** [comment]
It only works with two progress bars. If you want to have more than two values displayed, it is not working
