### ISSUE TITLE
can you add d.ts file version 2.0.1

### ISSUE THREAD

**Issue by hnsylitao** [kevinsqi/react-circular-progressbar#108]
can you add d.ts file version 2.0.1

**Comment by kevinsqi** [comment]
v2.0.1 is written in typescript and if you use the npm package in a project with typescript, the d.ts types should be included as part of the package.

Can you be more specific about the problem you're having? Is the typescript compiler complaining about missing types for react-circular-progressbar?

**Comment by hnsylitao** [comment]
thanks
maybe it's the reason for module upgrade.
causes IDE react-circular-progressbar types to temporarily not take effect
