### ISSUE TITLE
Issue after migrating to v2

### ISSUE THREAD

**Issue by red-coat** [kevinsqi/react-circular-progressbar#109]
Hi again, so it looks like a problem with the Circularprogressbar-path see screenshots attached.
Its gotten larger and im unsure why, if you look at my screenshots the user agents see's it as 190x190, but the whole svg is 200x200 in my screenshot you can see the path is visually larger, this can't be possible?

Have you seen anything similar bud? I'm confused.
Everything else went fine with update good job bro, some nice new features.

should probably mention i am scaling down the CircularProgressbar-background using     transform: scale(0.77); this is so i can achieve the look of a box shadow around the circle and the trail path running around the outside. Was working fine on the old version, looks like the Circularprogressbar-path has a larger offset from the middle or something?

any help will be much appreciated

![Screenshot 2019-07-30 at 13 10 41](https://user-images.githubusercontent.com/20561665/62128287-02b50100-b2cc-11e9-8fe6-075bae89efd2.png)
![Screenshot 2019-07-30 at 13 19 26](https://user-images.githubusercontent.com/20561665/62128612-b0281480-b2cc-11e9-81df-83f2fbdf75c5.png)

**Comment by red-coat** [comment]
I resolved this by using transform: scale(0.87) on the path in conjunction with using transform: scale(0.77) on the background
not sure if ive over or under thought this..

**Comment by kevinsqi** [comment]
Would be happy to look into it. Could you include the exact JSX you were using in both v1.x.x and v2.x.x, and the version numbers of the 1.x and 2.x progressbars you were using?

**Comment by kevinsqi** [comment]
Would still be happy to take a look if you get back to me with the old/new source code you were using - but I'm going to close this issue because it's been hanging around for a while.
