### ISSUE TITLE
Progress bar not rendering correctly in IE 11

### ISSUE THREAD

**Issue by EmBeaux** [kevinsqi/react-circular-progressbar#111]
### Summary of issue
 - When rendering a `CircularProgressbarWithChildren` in IE11 and Edge the progress is not filled in correctly until you hover and update the component.

 - I'm not entirely sure what is causing this but here is what the code is for the piechart
```
<div style={{ width: "96px", padding: "0", margin: "0" }}>
          <CircularProgressbarWithChildren
            backgroundPadding={0}
            circleRatio={1}
            value={percentage}
            strokeWidth={10}
            styles={buildStyles({
              pathColor: colors.secAction
            })}
          />
        </div>
```

_note_ This gif is taken from a VM
![questionnaire card render glitch](https://user-images.githubusercontent.com/43078490/62554264-d440a400-b83e-11e9-85b2-d0f4c102c0ee.gif)

### Your environment
 - This only happens in IE 11 and Edge.

**Comment by EmBeaux** [comment]
Changing the stroke width to be below 7 fixed it, but I would love to not change it from the stroke width of 10 I already have.

**Comment by EmBeaux** [comment]
So I ended up hacking a change for IE and Edge

I made this check that checked the browser to see if it is IE or Edge
`const isMSIEOrEdge = window.navigator.userAgent.indexOf("Trident/7") > -1 || /Edge/.test(navigator.userAgent);`


And i did the following:
```
        <div
          style={{
            width: "96px",
            padding: "0",
            margin: "0",
            position: "relative"
          }}
        >
          <CircularProgressbarWithChildren
            backgroundPadding={0}
            circleRatio={1}
            value={percentage}
            strokeWidth={isMSIEOrEdge ? 6 : 10}
            styles={buildStyles({
              pathColor: colors.secAction,
              strokeLinecap: "square"
            })}
          >
            {isMSIEOrEdge && (
              <div
                style={{
                  width: "87px",
                  padding: "0",
                  margin: "0",
                  position: "absolute",
                  top: /Edge/.test(navigator.userAgent) ? "5px" : "-54px",
                  left: "4px"
                }}
              >
                <CircularProgressbarWithChildren
                  backgroundPadding={0}
                  circleRatio={1}
                  value={percentage}
                  strokeWidth={6}
                  styles={buildStyles({
                    pathColor: colors.secAction,
                    strokeLinecap: "square"
                  })}
                />
              </div>
            )}
          </CircularProgressbarWithChildren>
        </div>
```
<img width="445" alt="Screen Shot 2019-08-06 at 5 21 00 PM" src="https://user-images.githubusercontent.com/43078490/62578224-9a879180-b86e-11e9-996d-334c45ab7977.png">


I basically nested 2 progress circles inside each other and adjusted the styles accordingly for IE and Edge. I also only did this for IE and Edge so we could have normal styles on chrome, firefox, safari etc.

**Comment by EmBeaux** [comment]
reopened because this isn't really a solution.

**Comment by kevinsqi** [comment]
Yeah.. this is unfortunate, but if it's a bug in IE, I'm not optimistic that there's going to be a great workaround. I can take a closer look sometime soon but I'm not sure I'll be able to find anything.

**Comment by kevinsqi** [comment]
Closing this due to IE11 being sunsetted.
