### ISSUE TITLE
Updating Progress Bar State Too Fast Causes Bar To Fill Up Partially

### ISSUE THREAD

**Issue by sqiii** [kevinsqi/react-circular-progressbar#116]
### Summary of issue

Hi - thanks for making this neat progress bar, nice API and everything. 

I've updated this because I've been exploring the problem further and it looks like the drawing capabilties of the progress bar SVGs aren't fast enough to keep up with fast state updates. 

I have some file upload functionality and apparently it runs too fast on Google Chrome, I discovered that the progress bar works fine on Internet Explorer and the state updates are far enough apart for it to be able to draw correctly. 

Seems like a tough issue to fix given how expensive it is to draw SVGs that fast - I think the solution for the time being is to have a debounce on state updates. 

_If applicable, add screenshots to help explain your problem._
![image](https://user-images.githubusercontent.com/54593592/65797386-21553e00-e13d-11e9-867a-7914fe00105f.png)

### Reproducible example
Here's a reproducible example that uses a for loop to mutate the percentage value. Check it out by using the value in any progress bar, they'll be unable to keep up and fill partially. https://codesandbox.io/s/base-react-circular-progressbar-examples-ldcgx?fontsize=14
In my app I have a functional component being passed props from redux which updates state as files get uploaded- the upload percentage is being calculated like this. 

`const uploadProgressPercentage = (Math.round((uploadProgress.uploadedFiles / uploadProgress.totalFiles)*100)) || 0;`

And this is how I have the progress bar laid out. What's weird is that the percentage displays fine all the way to a 100 but the progress bar doesn't... 
`                                            <CircularProgressbarWithChildren value={uploadProgressPercentage}>
                                                {/* Put any JSX content in here that you'd like. It'll be vertically and horizonally centered. */}
                                                <img style={{ width: 40, marginTop: -5 }} src="https://i.imgur.com/b9NyUGm.png" alt="doge" />
                                                <div style={{ fontSize: 12, marginTop: -5 }}>
                                                    <strong>{`${uploadProgressPercentage}%`}</strong> mate
                                                </div>
                                            </CircularProgressbarWithChildren>`

### Your environment
Windows 10
_What browser version were you using?_
Google Chrome, Internet Explorer

Would appreciate a look to see if I'm missing anything. Thanks som uch.

**Comment by kevinsqi** [comment]
Sorry I didn't get to look at this yet - is this working for you now?
