### ISSUE TITLE
pathColor not work

### ISSUE THREAD

**Issue by EdDevs2503** [kevinsqi/react-circular-progressbar#117]
I did a atemtp to do this:

![image](https://user-images.githubusercontent.com/45980184/66505503-855ef700-ea99-11e9-8584-3b18d30e4e29.png)

But the color of circular bar not work 

![image](https://user-images.githubusercontent.com/45980184/66505588-a7f11000-ea99-11e9-977a-0b108074599c.png)

**Comment by kevinsqi** [comment]
I'm seeing pathColor work in the examples I have (under "custom colors"): https://codesandbox.io/s/vymm4oln6y

Can you fork this codesandbox and provide a small example that demonstrates the issue? It would also help to provide your OS, browser, and the version of react-circular-progressbar you're using. https://codesandbox.io/s/reactcircularprogressbar-issue-template-3zm3j

**Comment by kevinsqi** [comment]
@EdDevs2503 were you able to see my previous comment or manage to get it to work? pathColor should definitely be working.
