### ISSUE TITLE
Progress higher than 100

### ISSUE THREAD

**Issue by lucbas** [kevinsqi/react-circular-progressbar#118]
### Problem description

_What a great project, thank you a lot!
We are trying to create an Apple Watch-styled progress circle and the only thing we have left is to enable the progress to be higher than 100. Do you have an idea on how to achieve this?_

_Appreciate your work!_

![apple-watch-activity-ring](https://user-images.githubusercontent.com/14868134/66636986-7cddfc00-ec12-11e9-9bc6-18639b9629ca.jpg)

**Comment by kevinsqi** [comment]
Thank you for the kind words!

There are a few different features needed to achieve the mockup you included:

1. Having the path intersect itself and appear to be "on top" of itself
2. Box shadow at the end of the path
3. A subtle color gradient along the path

I believe the combination of these features is difficult to achieve with svg, and given the niche use case, I'm afraid that implementing this is not in scope for this component. Feel free to fork it and see what you can do, though!

**Comment by kevinsqi** [comment]
No idea, haha. Couldn't find anything relevant to that overlapping effect - might not even be feasible with SVG paths.

**Comment by HarshiniRaavula** [comment]
Hi @L-U-C-K-Y ,

I too have a similar requirement to overlap when progress is more than 100. Do we have any further progress on this usecase ?

**Comment by L-U-C-K-Y** [comment]
> Hi @L-U-C-K-Y ,
> 
> 
> 
> I too have a similar requirement to overlap when progress is more than 100. Do we have any further progress on this usecase ?

Hi @HarshiniRaavula 

Unfortunately, it's not possible with this lib, but check out this video to create it from scratch: https://youtu.be/g5O2GJ1r9D4
