### ISSUE TITLE
Inner circle in circular progress bar

### ISSUE THREAD

**Issue by premzetwerk** [kevinsqi/react-circular-progressbar#119]
### Problem description

It would be great if we can provide the feature to add inner circle.

**Comment by kevinsqi** [comment]
I'm not currently planning to add a feature like this to the base library. However, if I'm understanding the feature request correctly, I think you can achieve this with some crafting using `CircularProgressbarWithChildren`:

<img width="600" alt="Screen Shot 2019-10-22 at 3 22 41 PM" src="https://user-images.githubusercontent.com/396006/67339417-13969c80-f4e0-11e9-8b14-61e44b86a643.png">

^ this example is now in the codesandbox examples: https://codesandbox.io/s/vymm4oln6y

Does this get you what you need @premzetwerk?

**Comment by kevinsqi** [comment]
^ I think this solution should cover what you need, but let me know if that doesn't work for you and we can re-open this. Thanks!
