### ISSUE TITLE
Circular Progress Bar with Children for React Native

### ISSUE THREAD

**Issue by Nsingh0007** [kevinsqi/react-circular-progressbar#126]
Circular Progress Bar with Children because i want to use RadialSeparators for React Native. 

**### Problem description**
Circular Progress Bar with Children because i want to use RadialSeparators in react native so can you please find some way for make it supportable.

**_Describe what you'd like to be able to accomplish. Including a rough sketch or screenshot can be helpful._**

Circular Progress Bar with Children because i want to use RadialSeparators in react native so can you please find some way for make it supportable.

### Suggested solution (optional)

_Suggest a solution that would solve the problem you have. For example, this may involve adding a new prop, changing an existing prop, or adding a new exported component._

**Comment by kevinsqi** [comment]
Unfortunately, React Native is outside the scope of this project, which can only work for web. See this: https://github.com/kevinsqi/react-circular-progressbar/issues/74
