### ISSUE TITLE
How can I use it to show uploading/downloading speed?

### ISSUE THREAD

**Issue by vivekkumar16** [kevinsqi/react-circular-progressbar#127]
Say, I want to download a large file or I want to upload a file, can I use it in such a case to show how much time is remaining for that operation to happen?

**Comment by kevinsqi** [comment]
Sure, you could use this component to do that. This component just needs a percentage value - how you get that value is up to you.

One way to do that could be to [create an XHR request and listen for the "progress" event](https://github.com/georgeOsdDev/react-fileupload-progress/blob/master/src/components/FileUploadProgress.js#L100-L154), or perhaps to [use axios](https://stackoverflow.com/a/50479326/341512). In the event handler for either case, you'd want to call `setState({ value: ... })` to adjust the value being passed to `<CircularProgressbar value={state.value} />`. Hope this helps.
