### ISSUE TITLE
Browser queries must be an array or string. Got object.

### ISSUE THREAD

**Issue by caseykey** [kevinsqi/react-circular-progressbar#128]
### Summary of issue

I am converting my create-react-app to Gatsby, and I implemented the circular progress bar. When attempting to build my app using `gatsby build`, I get this error:
``` ERROR 

Unknown error from PostCSS plugin. Your current PostCSS version is 6.0.23, but autoprefixer uses 7.0.26. Perhaps this is the source of the error below.


 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

Browser queries must be an array or string. Got object.

File: node_modules/react-circular-progressbar/dist/styles.css
```

I updated PostCSS to 7.0.26 using npm i postcss but it still says I'm on the old version. 

### Reproducible example

You can see this error if you checkout https://github.com/caseykey/caseykey.github.io/tree/circular-error

### Your environment

Latest Google Chrome, developing on WSL.

**Comment by JCTubio** [comment]
issue solved:
https://stackoverflow.com/questions/59707001/error-after-converting-create-react-app-to-gatsby-webpack-browser-queries-must

**Comment by kevinsqi** [comment]
Thanks @JCTubio! Looks like this was an issue with the app configuration; is the issue now fixed for you @caseykey?

**Comment by caseykey** [comment]
Yes, it was an issue with not having the correct plugins installed for gatsby, mainly PostCSS. I also needed to add a postcss configuration file to my project's root directory. More info is at the above StackOverflow post.

**Comment by kevinsqi** [comment]
Thanks for the update! Glad to hear it's resolved now.
