### ISSUE TITLE
Set the size of progress bar...

### ISSUE THREAD

**Issue by rlyle** [kevinsqi/react-circular-progressbar#134]
## 🚀 Feature request
Set the size of the progress bar..

### Problem description
Reading over all your docs, I don't see anyway to actually set the size of the progress bar, am I missing something? typically, you just put "size=20" into the properties and you'd think that would work.

### Suggested solution (optional)

_Suggest a solution that would solve the problem you have. For example, this may involve adding a new prop, changing an existing prop, or adding a new exported component._

**Comment by rlyle** [comment]
Nevermind.. :)

Put a <div style={{width: 200, height: 200}}> around the progress bar and that worked :)

**Comment by kevinsqi** [comment]
yup, that's the way to go :) I should make this clearer in the README, though.
