### ISSUE TITLE
Adding background image instead of filling background

### ISSUE THREAD

**Issue by amirhosseinak20** [kevinsqi/react-circular-progressbar#136]
Hi,
thanks for your component.
I want to know how can i add a background image to the CircularProgressbar

**Comment by kevinsqi** [comment]
Take a look at the "Arbitrary content" example in the codesandbox, which uses CircularProgressbarWithChildren:

https://codesandbox.io/s/vymm4oln6y

![Screen Shot 2020-03-31 at 11 33 34 PM](https://user-images.githubusercontent.com/396006/78106360-17d8b700-73a8-11ea-9bad-fb80a3c4691a.png)

That should allow you to use a background image. Let me know if it doesn't address what you need.
