### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by adnaneghalem** [kevinsqi/react-circular-progressbar#137]
## 🚀 Feature request
It would be really nice that it could work with React Native :D
### Problem description

_Describe what you'd like to be able to accomplish. Including a rough sketch or screenshot can be helpful._

### Suggested solution (optional)

_Suggest a solution that would solve the problem you have. For example, this may involve adding a new prop, changing an existing prop, or adding a new exported component._

**Comment by kevinsqi** [comment]
This wouldn't work with react-native because it relies on <svg> tags which aren't supported in react-native. See: https://github.com/kevinsqi/react-circular-progressbar/issues/74

As an alternative, you could check out something like https://github.com/bartgryszko/react-native-circular-progress.
