### ISSUE TITLE
no progress made?

### ISSUE THREAD

**Issue by iraizo** [kevinsqi/react-circular-progressbar#139]
### Summary of issue

_Please describe what the problem is._ 
no progress when running production build instead of dev build

_If applicable, add screenshots to help explain your problem._
https://jelbrek.icu/k9b849ey.png

### Reproducible example

_[Fork this Codesandbox](_https://codesandbox.io/s/reactcircularprogressbar-issue-template-3zm3j_) and modify it to demonstrate the issue you're having._
I could not reproduce it on codesandbox but ill leave a 1:1 copy of the site here: https://github.com/iraizo/switchbla.de/ 

### Your environment

_What browser version were you using?_
firefox nightly/firefox/chrome

**Comment by kevinsqi** [comment]
Looks like you need to import the CSS styles with e.g. `import 'react-circular-progressbar/dist/styles.css';`. Let me know if that doesn't do it.

**Comment by iraizo** [comment]
have you taken a look at the project i sent, i imported it and it works in the developement version

**Comment by iraizo** [comment]
https://github.com/iraizo/switchbla.de/blob/master/pages/_app.tsx#L6

**Comment by kevinsqi** [comment]
Yeah, I did take a look at your project. If it works in development and not production, it's very likely a configuration issue in your CSS in production, and it's not really my job to help you debug that. You should look at what's different between dev and prod - taking a quick look my guess is that purgecss might be stripping out the CSS for some reason: https://github.com/iraizo/switchbla.de/blob/master/postcss.config.js

**Comment by iraizo** [comment]
I will disable postcss and see what happens,
