### ISSUE TITLE
Text not centered

### ISSUE THREAD

**Issue by reifnotreef** [kevinsqi/react-circular-progressbar#140]
### Summary of issue

Text is not centered.
The only styling I am applying: styles={buildStyles({ pathColor: '#0065B1', textColor: '#0065B1' })}
[chrome](https://imgur.com/a/DbNY2zz)
[edge](https://imgur.com/gallery/UEeE0bL)

### Your environment

Chrome: Version 81.0.4044.122 (Official Build) (64-bit)
Edge: Microsoft Edge 44.19041.1.0, Microsoft EdgeHTML 18.19041

**Comment by reifnotreef** [comment]
I decided to give the WithChildren a shot and it works perfectly in terms of keeping the <p> inside centered.

**Comment by kevinsqi** [comment]
Sorry to hear you're running into issues. I'm seeing the progressbar centered in my examples, so I'm wondering what's different about your case - could you help reproduce the issue in a Codesandbox? https://codesandbox.io/s/reactcircularprogressbar-issue-template-3zm3j

**Comment by reifnotreef** [comment]
@kevinsqi  Thanks for checking it out. Turns out there is some strange css/divs that is affecting it's position. For some reason the WithChildren works fine though.

**Comment by bensquire** [comment]
Thanks for the library @kevinsqi. I too had a similar issue and `CircularProgressbarWithChildren` over `CircularProgressbar` allowed me to get this centred properly.

Looking at the example above, I used the macOS screen capture tool to measure the distances between text and top/bottom and I don't think it is centred...
