### ISSUE TITLE
Adding a custom SVG as a leading point 

### ISSUE THREAD

**Issue by ahmad-crossplatform** [kevinsqi/react-circular-progressbar#142]
### Problem description
Is it possible to add a custom header for the progress ?  something similar to the image below 

![image](https://user-images.githubusercontent.com/30656865/81823451-9f335180-9534-11ea-8846-6790dee1dd4e.png)

**Comment by kevinsqi** [comment]
That's a bit too specific to add to the component itself, but you'd be able to implement that by overlaying another element on top of the progressbar with `CircularProgressbarWithChildren`: https://github.com/kevinsqi/react-circular-progressbar/blob/master/README.md#adding-arbitrary-text-or-content-inside-the-progressbar. Hope that helps.

**Comment by kevinsqi** [comment]
If you're referring more to the circle marker at the end of the blue path, that is being tracked in this issue: https://github.com/kevinsqi/react-circular-progressbar/issues/97
