### ISSUE TITLE
New line of text

### ISSUE THREAD

**Issue by Mohammed9909** [kevinsqi/react-circular-progressbar#150]
Hi
I hope you are well
I want to put new line text into the text inside circular-progress bar
How is that can you help my please

Regards

**Comment by ahalawani001** [comment]
Hello, did you solve your issue? If yes can you share how please

**Comment by Amarjit-ph** [comment]
Hello Developers, We need new line in text inside the circle

**Comment by kevinsqi** [comment]
Sure, you can put arbitrary react elements inside the progressbar with CircularProgressbarWithChildren. Take a look at the "Arbitrary content" example in the examples here: https://codesandbox.io/s/vymm4oln6y?file=/index.js:4158-4602

You could do something like this:

```jsx
      <CircularProgressbarWithChildren value={66}>
        {/* Put any JSX content in here that you'd like. It'll be vertically and horizonally centered. */}
        <div style={{ fontSize: 12, marginTop: -5 }}>
          Hello<br />
          React
        </div>
      </CircularProgressbarWithChildren>
```

Hope this helps. Feel free to reopen if you have further issues.
