### ISSUE TITLE
Icon in middle instead of text.

### ISSUE THREAD

**Issue by amoses12** [kevinsqi/react-circular-progressbar#155]
### Problem description

I'd like to be able to add an icon in the middle of my progress bar as opposed to just percentage text Like so.
![Screen Shot 2020-09-29 at 11 45 42 AM](https://user-images.githubusercontent.com/33231032/94596460-611b9d80-0249-11eb-938b-809fc4e37376.png)

Is there any way to pass something like an icon to the "text" prop?

**Comment by kevinsqi** [comment]
You can do this with CircularProgressBarWithChildren: https://github.com/kevinsqi/react-circular-progressbar/blob/master/README.md#adding-arbitrary-text-or-content-inside-the-progressbar

Let me know if that doesn't cover what you need!

**Comment by amoses12** [comment]
Ah perfect! Can't believe I didn't see that one. Thanks for your help!
