### ISSUE TITLE
98% looks like 100% with round corner

### ISSUE THREAD

**Issue by Lie8466** [kevinsqi/react-circular-progressbar#158]
### Summary of issue

Please describe what the problem is - this will help me be able to track down the issue. If applicable, add screenshots to help explain your problem.

`<CircularProgressbar value={98} text={`${98}%`} />`

but displays like 100%

![image](https://user-images.githubusercontent.com/29086796/99021443-a3036780-259b-11eb-8fa8-4d18554cbb5b.png)

Is there any suggestion to quick solve this problem？(stroke width and round corner maintain current status)

Thanks

### Reproducible example

https://codesandbox.io/s/base-react-circular-progressbar-examples-forked-r41n9?file=/index.js

### Your environment

* What browser version were you using?

Chrome

* What version of react-circular-progressbar are you using?

2.0.1

**Comment by keithpickering** [comment]
I guess you could just add a condition to decrease the rendered value if it's within that questionable range, while still showing the actual value in the text. Something like this

```
<CircularProgressbar value={value > 97 && value < 100 ? 97 : value} text={${value}%} />
```

**Comment by Lie8466** [comment]
Get it! Thanks.
