### ISSUE TITLE
how to set {border: solid}  Circular progress bar

### ISSUE THREAD

**Issue by PokerJava** [kevinsqi/react-circular-progressbar#163]
<img width="338" alt="Screen Shot 2564-01-30 at 22 13 31" src="https://user-images.githubusercontent.com/26649959/106359982-a3183580-6348-11eb-8dbe-7d0d1a8564d6.png">

how to set {border: solid}  Circular progress bar

**Comment by tomatobybike** [comment]
you can set background and backgroundPadding and backgroundColor,like this   
`        <CircularProgressbar
          value={percentage}
          strokeWidth={50}
          background={true}
          backgroundPadding={1}
          styles={buildStyles({
            strokeLinecap: 'butt',
            pathColor: '#4EB857',
            trailColor: '#FFF',
            backgroundColor: '#4EB857'
          })}
        />`
