### ISSUE TITLE
Is a Half Circle or Semir Circle possible ?  To save some  screen space. 

### ISSUE THREAD

**Issue by Krammig** [kevinsqi/react-circular-progressbar#206]
Just wondering if to is possible have a Horizontal semi circle / half circle please ?

I am wanting to show a Countdown in Seconds preferably decrementing however the standard incrementing will do. 

Example 30 seconds that will animate in 30 chunks and the text counter accordingly as an integer. 

The main thing is just a semi-circle to same the screen space.

Thanks

**Comment by Nikola-Milovic** [comment]
@Krammig  you can check out https://codesandbox.io/s/vymm4oln6y?file=/index.js

There you will find `circleRatio={0.75}` property, you can set it to 0.5 and I think that would work as intended

**Comment by kevinsqi** [comment]
Thanks for the suggestion @Nikola-Milovic! That's how I'd approach it. See this thread for more info: https://github.com/kevinsqi/react-circular-progressbar/issues/49
