### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by ConnorKemp** [kevinsqi/react-circular-progressbar#212]
## Heres my error: 
export 'default' (imported as 'CircularProgressbar') was not found in 'react-circular-progressbar' (possible exports: CircularProgressbar, CircularProgressbarWithChildren, buildStyles)

**Comment by kevinsqi** [comment]
Please include your code next time! But try `import { CircularProgressbar } from 'react-circular-progressbar` instead of using default import.
