### ISSUE TITLE
Doesn't  work with react 18 above

### ISSUE THREAD

**Issue by KristofKreimeyer** [kevinsqi/react-circular-progressbar#214]
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"18.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0 || ^16.0.0 || ^17.0.0" from react-circular-progressbar@2.0.4

**Comment by jasonwee** [comment]
me too

**Comment by deathm1** [comment]
me too

**Comment by jts8257** [comment]
me too

**Comment by kevinsqi** [comment]
Sorry for the delay here; this should be fixed in 2.1.0 with https://github.com/kevinsqi/react-circular-progressbar/pull/209. Let me know if there are other issues here.
