### ISSUE TITLE
Dashboard style progress bar

### ISSUE THREAD

**Issue by nbruno** [kevinsqi/react-circular-progressbar#49]
Is there any way to customize the display of the progress bar to display like a "dashboard" progress indicator, similar to the dashboard progress bar from ant design https://ant.design/components/progress/

![screen shot 2018-03-15 at 7 24 06 pm](https://user-images.githubusercontent.com/1942995/37496007-7c1e6832-2886-11e8-8f69-ef1af9251061.png)

**Comment by jeremywho** [comment]
I added support for this here:
https://github.com/jeremywho/react-circular-progressbar/pull/1

I'm not submitting a PR at the moment as `counterClockwise` is broken. 

If you have a suggestion for getting that to work, let me know, I'll update and add unit tests and PR.

**Comment by kevinsqi** [comment]
@jeremywho that looks neat - sorry I haven't had time to dig in yet.

**Comment by lchandramohan** [comment]
any update on this?

**Comment by kevinsqi** [comment]
Not yet. I'd like to take a pass at it soon, though.

**Comment by kevinsqi** [comment]
This is now possible in v1.2.0 with the `circleRatio` prop and CSS rotation, based on @jeremywho's helpful initial PR which I fleshed out in #80.

To do this:

<img width="124" alt="Screen Shot 2019-04-28 at 9 21 08 PM" src="https://user-images.githubusercontent.com/396006/56876371-af48c380-69fb-11e9-81b4-1868582c9b1e.png">

You'd write:

```jsx
          <CircularProgressbar
            percentage={66}
            text={`${66}%`}
            circleRatio={0.75}  /* Make the circle only span 3/4ths of a full diameter */
            styles={{
              trail: {
                strokeLinecap: 'butt',
                transform: 'rotate(-135deg)',
                transformOrigin: 'center center',
              },
              path: {
                strokeLinecap: 'butt',
                transform: 'rotate(-135deg)',
                transformOrigin: 'center center',
              },
            }}
          />
```

Right now it's slightly cumbersome because you have to adjust `transform: rotate` whenever you change `circleRatio`. I'm planning to add some abstractions to make this easier in the future.

cc @nbruno @jeremywho @lchandramohan

**Comment by kevinsqi** [comment]
The syntax is now somewhat nicer in v2.0.0 with buildStyles, e.g.:

```jsx
const value = 66;

<CircularProgressbar
  value={value}
  text={`${value}%`}
  circleRatio={0.75}
  styles={buildStyles({
    rotation: 1 / 2 + 1 / 8,
    strokeLinecap: "butt",
    trailColor: "#eee"
  })}
/>
```

**Comment by aaron170** [comment]
Hello.

Can we add ticks around the meter. Like we have in a Gauge chart.?

**Comment by garrett-gottlieb** [comment]
Follow-up question: how would one adjust the height of the SVG based on this `circleRatio` so there's no empty space at the bottom?

```ts
      <CircularProgressbar
        value={fill}
        circleRatio={0.5}
        styles={buildStyles({
          rotation: 3 / 4,
          strokeLinecap: 'butt',
          trailColor: COLOR.PURPLE,
          textColor: COLOR.WHITE,
        })}
      />
```

I've tried `margin-bottom: -50%` but that's not working.

**Comment by HoussemDjeghri** [comment]
@garrett-gottlieb you can add a parent div on top of the `CircularProgressbar` that has the height you want and with the property `overflow:clip` to cut the unwanted space.
`progressContainer:{
      width: 200,
      height:150,
      overflow: "clip"
  }`

**Comment by ViniTeider** [comment]
@HoussemDjeghri this doesnt work since the progress bar resizes to fit the div, did any one find another solution?
