### ISSUE TITLE
Parameterize max percentage

### ISSUE THREAD

**Issue by LeonardoVaquel** [kevinsqi/react-circular-progressbar#71]

**Comment by iqnivek** [comment]
This is suggesting to have something like a maxPercentage prop, right?

You can do that now with a small wrapper component: https://codesandbox.io/s/6z64omwv3n

I agree that this would be better directly implemented in the component, though. My instinct would be to add `value` and `maxValue` (and maybe `minValue` as well?) props and remove the `percentage` prop. Could be done as a minor version which deprecates `percentage`, and then a major version that removes it entirely. What do folks think about that?

**Comment by kevinsqi** [comment]
This is now possible with `props.minValue` and `props.maxValue` in v2.0.0.
