### ISSUE TITLE
Allow negative padding on background

### ISSUE THREAD

**Issue by jdt3969** [kevinsqi/react-circular-progressbar#76]
Allow for negative padding on the background to allow background to be inside path. This is especially nice for semi-transparent trails. 

`backgroundPadding={-strokeWidth}`, `backgroundPadding={-strokeWidth / 2}`, and `backgroundPadding={-strokeWidth * 2}` give interesting effects.

**Comment by jdt3969** [comment]
Hacked together a working version https://github.com/jdt3969/react-circular-progressbar/commit/9c0f69f11ed365eb1b1df6d86e5c68c6485cdbc5

**Comment by kevinsqi** [comment]
Thanks for the suggestion @jdt3969! I'd prefer not to add this additional complexity for what appears to be a relatively niche use case, though.

As a workaround, I think you could also achieve this by using the [arbitrary content overlay method](https://github.com/kevinsqi/react-circular-progressbar#customizing-the-textcontent-inside-progressbar) to put a smaller SVG circle `<svg ...><circle ...></svg>` inside the path.

If other folks mention that they want this functionality, I'd be willing to reconsider and re-open this.
