### ISSUE TITLE
[QUESTION]: indeterminate progress bar

### ISSUE THREAD

**Issue by taverasmisael** [kevinsqi/react-circular-progressbar#79]
Is there a way (even in the foreseeable feature) to use this as an indeterminate circular progress bar to create a kind of loading effect?

**Comment by kevinsqi** [comment]
No current plans to build it into the component. However, played around with it for a bit and I think you could use CSS animations to create a `LoadingProgressbar` component on top of react-circular-progressbar that looks pretty good!

Result:

![2019-04-25 22 13 33](https://user-images.githubusercontent.com/396006/56784838-6d274400-67a7-11e9-8701-a20cb6005d09.gif)

Check out the code: **https://codesandbox.io/s/mqqq8r0kk8**

Does that cover your use case?

**Comment by taverasmisael** [comment]
OMG! Thanks you so much. Yes, it does. 

Closing.

**Comment by kevinsqi** [comment]
Glad to hear it! 😄
