### ISSUE TITLE
npm not install src directory

### ISSUE THREAD

**Issue by 6R36** [kevinsqi/react-circular-progressbar#81]
npm not install src directory, but this directory is necessary for source-map.
Could you fix this please.

**Comment by kevinsqi** [comment]
I'm happy to help investigate the issue you're having. I think that directly adding `src` to the built npm package is unusual, however. Can you give some more detail on the exact problem you're having with sourcemaps? A [codesandbox example](https://codesandbox.io/s/vymm4oln6y) of what's breaking would be super helpful.

**Comment by kevinsqi** [comment]
FYI, I just released v1.2.1 which handles sourcemaps a little differently now due to using rollup instead of tsc for package building. You may want to give that version a shot to see if your sourcemap issue is resolved.

**Comment by 6R36** [comment]
Working perfect with v1.2.1. Thank.

**Comment by kevinsqi** [comment]
Glad to hear it!
