### ISSUE TITLE
Property 'background' is missing in type '{ value: number; text: string; styles: CircularProgressbarStyles; }'

### ISSUE THREAD

**Issue by MervLim** [kevinsqi/react-circular-progressbar#91]
<VisibilitySensor>
                        {({ isVisible }) => {
                          const percentage = isVisible ? 15 : 0;
                          return (
                            <CircularProgressbar
                              value={percentage}
                              text={`${percentage}%`}
                              styles={buildStyles({
                                pathColor: '#e10000',
                                textColor: '#a6a8aa',
                              })}
                            />
                          );
                        }}
                      </VisibilitySensor>

This is my code and i got an error saying that property background is missing. What am i doing wrong ?

**Comment by kevinsqi** [comment]
hmm, I wasn't able to reproduce in vanilla JS or typescript: https://codesandbox.io/s/5t1wx

If you're still seeing the problem, can you create a Codesandbox demonstrating the problem? Thanks!

**Comment by kevinsqi** [comment]
@MervLim are you able to reproduce the problem in Codesandbox?

**Comment by MervLim** [comment]
I couldn't reproduce the problem in Codesandbox but i'm still having the error locally.

**Comment by kevinsqi** [comment]
Okay, understood. Sorry you're still having issues! I'll need more information to help you resolve the problem though - I can only help if I can . Could you include these details:

* The full stack trace of the error
* The full source file (would like to see your import statements)
* A link to the repository you're working on (optional, only if possible)
* The environment - are you using typescript or flow or js/webpack? What version of typescript/flow?
* The version of react-circular-progressbar you're on

Thanks!

**Comment by kevinsqi** [comment]
Closing this as I haven't heard from it in a while - @MervLim if this is still an issue don't hesitate to re-open.
