### ISSUE TITLE
how to create with Steps

### ISSUE THREAD

**Issue by Nicosoft** [kevinsqi/react-circular-progressbar#92]
Hi there,

## 🚀 Feature request
Circle progress with Steps
### Problem description
Im trying to accomplish this look: Add Steps to the circle
<img width="143" alt="Screen Shot 2019-05-29 at 4 29 26 pm" src="https://user-images.githubusercontent.com/4625910/58534552-f9a5a600-822e-11e9-949a-7d78ca2a1245.png">

This will show to the user how far he is from the new level. 

### Suggested solution (optional)
I was thinking maybe I could achieve this (see below) if I could define the number of segments or steps
<img width="122" alt="Screen Shot 2019-05-29 at 4 23 57 pm" src="https://user-images.githubusercontent.com/4625910/58534652-35407000-822f-11e9-9399-3cd3cf405d84.png">
By the way, this latest example appears in the README but it is not shown in the code sandbox

How could it be done?

Thanks.

**Comment by kevinsqi** [comment]
This is achievable, but it's not built-in to the component. Instead you can build your own "step" markers and overlay them on top of the progressbar using `CircularProgressbarWithChildren`. 

Check out this example: https://codesandbox.io/s/segmented-react-circular-progressbar-v201-m9wgc

In the example, the `RadialProgressbars` component allows you to customize the number of segments and color of the "step" markers.

@Nicosoft does this get you what you need?
