### ISSUE TITLE
Failed Compiling in React

### ISSUE THREAD

**Issue by diipacheco** [kevinsqi/react-circular-progressbar#93]
### Summary of issue

Basically, i getting one failure when the React compiles my component that contains the import of the library. Somehow the component doesn't receives the default export from the library, that results in a massage log "Failed to Compile". 

**The import on the component:**
`import CircularProgressbar from "react-circular-progressbar";`

**The code of component RCPB encapsulated in a div JSX**
`                          <div>
				<CircularProgressbar
					styles={{
						root: { width: 24 },
						path: { stroke: "#232f3e" }
					}}
					strokeWidth={10}
					percentage={60}
				/>`

### The message on the Browser

![image](https://user-images.githubusercontent.com/44613606/58578745-daebe300-821f-11e9-9c81-0074a04f6ce6.png)

### My environment

I'm using the current version of RCPB (2.0.0), the 16.8.6 version of React and React DOM and the 74.0.3729.169 version of the Chrome.

**Comment by bennysghost** [comment]
how was this resolved?

**Comment by kevinsqi** [comment]
Assuming @diipacheco was using react-circular-progressbar >= 2.0.0, the import statement was wrong. Per the docs, you need to now do a named import instead of a default import:

```
import { CircularProgressbar } from "react-circular-progressbar";
```
