### ISSUE TITLE
Progressbar animation won't work in microsoft edge

### ISSUE THREAD

**Issue by sergeycw** [kevinsqi/react-circular-progressbar#95]
Hi! Thanks for the great component!

But I have an issue - it won't work in microsoft edge (18 for example)

![Screenshot from 2019-06-04 09 57 37](https://user-images.githubusercontent.com/36540337/58858422-2be05900-86b0-11e9-84b1-fac0b68f4300.jpeg)

**Comment by kevinsqi** [comment]
Yeah, I was able to reproduce in Edge 18. Just to clarify: the progressbar works for static values in Edge just fine, but the CSS animations are faulty when transitioning from one value to another.

It actually appears to be dependent on the specific values involved - for instance, if you set props.value from 0 to 40, it will break:

<img src=https://user-images.githubusercontent.com/396006/58933583-9cbd5a80-871c-11e9-8056-0a33ee3dd6af.gif width=400 />

However, if you set props.value from 40 to 0, it works fine:

<img src=https://user-images.githubusercontent.com/396006/58933588-9f1fb480-871c-11e9-99cc-4862907180aa.gif width=400 />

I'm not clear what the exact issue is, but it seems to me that there are still specific aspects of SVG animation that may still be broken in Edge. I don't know that it's possible to fix these issues through the library itself.

**Here's my recommendation if you need animation in Edge**: implement the "Fully controlled animation" example in [this codesandbox](https://codesandbox.io/s/vymm4oln6y), which avoids the CSS animation issue by instead controlling the animation fully using props.value.

Let me know if this addresses the issue you have. Thanks!
