### ISSUE TITLE
Sample ProgressProvider doesn't update value

### ISSUE THREAD

**Issue by StevenMyers32** [kevinsqi/react-circular-progressbar#99]
Just a heads up. The ProgressProvider in the code sandbox doesn't update the value when `valueEnd` changes. That's at least how I expected it to behave. 

Here's a sample ProgressProvider with a fix (now with hooks): 

```
const ProgressProvider = ({ valueStart, valueEnd, children }) => {
  const [value, setValue] = useState(valueStart);
  useEffect(() => {
    setValue(valueEnd);
  }, [valueEnd]);

  return children(value);
};
```

**Comment by kevinsqi** [comment]
You're right - I didn't handle the valueEnd change case. I've updated the CodeSandbox with your implementation: https://codesandbox.io/s/react-circular-progressbar-with-initial-animation-0zk372m7l

Thanks @StevenMyers32!
